stages:
  - build
  - test
  
image: node:18

variables:
  YARN_CACHE_DIR: "$CI_PROJECT_DIR/.yarn-cache"

build-smart-contracts:
  stage: build
  needs: []
  before_script:
    - yarn install --frozen-lockfile --cache-folder $YARN_CACHE_DIR
  script:
    - yarn c
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/
        - node_modules/
      policy: pull-push
  artifacts:
    paths:
      - typechain
      - typechain-truffle
      - typechain-web3
    expire_in: 1 week

test-unit:
  stage: test
  timeout: 1h
  needs:
    - build-smart-contracts
  before_script:
    - yarn install --frozen-lockfile --cache-folder $YARN_CACHE_DIR
  script:
    - yarn test
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/
        - node_modules/
      policy: pull-push
