workflow:
  rules:
    - if: '$CI_OPEN_MERGE_REQUESTS != null && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "webide")'
      when: never
    - when: always

.test:
  stage: test
  image: node:20
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules/
      policy: pull
  before_script:
    - yarn install --frozen-lockfile

test-all:
  extends: .test
  script:
    - yarn test:all

# TODO: enable coverage reports
# test-coverage:
#   extends: .test
#   script:
#     - yarn test:coverage
